#!/bin/sh

xrandr --output HDMI-0 --auto --primary --right-of DP-1 &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd >/dev/null || sxhkd &

hostname=$(hostname)

if [ "$hostname" == "nixos" ]; then
	bspc monitor HDMI-0 -d I II III IV
	bspc monitor DP-1 -d I II III IV
elif [ "$hostname" == "t470" ]; then
	bspc monitor eDP-1 -d I II III IV V
fi

bspc config border_width 2
bspc config window_gap 4

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Steam monitor=HDMI-0 desktop=^4

pkill -q picom &
pkill -q polybar &
pkill -q flameshot &
pkill Discord &
pkill -q steam &
pkill -q kdeconnect-cli &
eww kill

/nix/store/$(ls -la /nix/store | grep polkit-kde-agent | grep '^d' | awk '{print $9}')/libexec/polkit-kde-authentication-agent-1 &
picom -b --config ~/.config/picom/picom.conf &
if [ "$hostname" == "nixos" ]; then
	polybar bar 2>&1 | tee -a /tmp/polybar.log &
fi
flameshot &
discord &
steam &
kdeconnect-cli &
eww daemon
eww open notifications
