#!/bin/sh

xrandr --output HDMI-0 --auto --primary --left-of DP-5 &
xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d  I II III IV V VI VII VIII IX X
bspc monitor DP-5 -d    I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

killall -q polybar
polybar mybar 2>&1 | tee -a /tmp/polybar.log & disown

killall -q Discord
discord & disown
